name: Go

on:
  push:
    branches: [master]
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  generate-tag-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate tag files
        uses: goreleaser/goreleaser-action@v2.7.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-aur-package:
    needs:
      - generate-tag-files

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate PKGBUILD
        run: ./build/scripts/generate-pkgbuild.py
        env:
          TARGET: ${{ matrix.target }}
          RELEASE_TAG: ${{ needs.create_release.outputs.release_tag }}

      - name: Publish peekprof to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: peekprof
          pkgbuild: ./pkgbuild/peekprof/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ needs.create_release.outputs.release_tag }}
          force_push: "true"
